### ISSUE TITLE
Add Translations via Twig

### ISSUE THREAD

**Issue by torstenhoegel** [nbayramberdiyev/slim-4-starter#2]
Hi there,

first of all, awesome template! I like your structure.

I am trying to rewrite a project made in slim3. A few years ago a translation was implemented using twig tags: `{% trans %}StringToTranslate{% endtrans %}` but sadly I am not able to get this working with your starter kit. I have tried following this tutorial https://symfony.com/doc/current/translation.html ...

Would you be able to help me with this?

Thanks in advance <3

**Comment by nbayramberdiyev** [comment]
Hey @torstenhoegel, yes, I will look what I can do for this. Thanks!

**Comment by torstenhoegel** [comment]
any updates on this? :)

**Comment by nbayramberdiyev** [comment]
Done in [`eb30855`](https://github.com/nbayramberdiyev/slim-4-starter/commit/eb308550c198cd1c8195227e4d2da8bf4d4b95be).
